
server:
  port: 9100
spring:
  application:
    name: gw

eureka:
  client:
    service-url:
      defaultZone: http://center.com:7900/eureka/

gw:
  anon:
    -/auth/login


zuul:
  # 网关匹配前缀
  prefix: /gateway
  # 网关转发后是否去掉前缀
  strip-prefix: true
